package endpoint

const (
	WsUrl = "wss://ws-subscriptions-clob.polymarket.com"
)

// API endpoints
const (
	CancelAll                     = "/cancel-all"
	CancelOrder                   = "/order"
	CreateApiKey                  = "/auth/api-key"
	GetApiKeys                    = "/auth/api-keys"
	ClosedOnly                    = "/auth/ban-status/closed-only"
	GetOrder                      = "/data/order/"
	PostOrder                     = "/order"
	Time                          = "/time"
	GetTrades                     = "/data/trades"
	GetOrderBook                  = "/book"
	DeleteApiKey                  = "/auth/api-key"
	GetMidpoint                   = "/midpoint"
	GetPrice                      = "/price"
	GetOpenOrders                 = "/data/orders"
	DeriveApiKey                  = "/auth/derive-api-key"
	GetLastTradePrice             = "/last-trade-price"
	GetMarkets                    = "/markets"
	GetMarket                     = "/markets/"
	GetPricesHistory              = "/prices-history"
	GetNotifications              = "/notifications"
	DropNotifications             = "/notifications"
	CancelOrders                  = "/orders"
	CancelMarketOrders            = "/cancel-market-orders"
	GetBalanceAllowance           = "/balance-allowance"
	IsOrderScoring                = "/order-scoring"
	GetTickSize                   = "/tick-size"
	GetNegRisk                    = "/neg-risk"
	AreOrdersScoring              = "/orders-scoring"
	GetSimplifiedMarkets          = "/simplified-markets"
	GetSamplingSimplifiedMarkets  = "/sampling-simplified-markets"
	GetSamplingMarkets            = "/sampling-markets"
	GetMarketTradesEvents         = "/live-activity/events/"
	GetOrderBooks                 = "/books"
	GetMidpoints                  = "/midpoints"
	GetPrices                     = "/prices"
	GetLastTradesPrices           = "/last-trades-prices"
	GetEarningsForUserForDay      = "/rewards/user"
	GetLiquidityRewardPercentages = "/rewards/user/percentages"
	GetRewardsMarketsCurrent      = "/rewards/markets/current"
	GetRewardsMarkets             = "/rewards/markets/"
	GetRewardsEarningsPercentages = "/rewards/user/markets"
	GetTotalEarningsForUserForDay = "/rewards/user/total"
	GetSpread                     = "/spread"
	GetSpreads                    = "/spreads"
	UpdateBalanceAllowance        = "/balance-allowance/update"
	PostOrders                    = "/orders"
	GetFeeRate                    = "/fee-rate"
	GetBuilderTrades              = "/builder/trades"
)
